# Datadog API credentials
datadog:
  api_key: YOUR_DATADOG_API_KEY        # Replace with your actual Datadog API key
  app_key: YOUR_DATADOG_APP_KEY        # Replace with your actual Datadog application key

# Slack webhook configuration
slack:
  webhook_url: https://hooks.slack.com/services/your/webhook/url  # Replace with your Slack incoming webhook URL
